env:
  browser: true
  es2021: true
  node: true
extends: airbnb
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
"react/prop-types": [<disabled>, { ignore: <ignore>, customValidators: <customValidator>, skipUndeclared: <skipUndeclared> }]
}
