name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_PASS }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: hamdielzard/wordeo
      
      - name: Build docker compose
        run: docker-compose build
      
      # github.ref_name returns the branch or tag name that triggered the job
      - name: Publish docker compose with tag
        run: docker-compose push hamdielzard/wordeo:${{ github.ref_name }}