version: '3.1'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  client:
    build: ./client
    image: hamdielzard/wordeo:${RELEASE_TAG}
    ports:
      - "3000:3000"
  server:
    build: ./server
    image: hamdielzard/wordeo:${RELEASE_TAG}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb