name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:
    # no input provided

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_PASS }}

        # github.ref_name returns the branch or tag name that triggered the job
      - name: Set release name
        run: export RELEASE_TAG=${{ github.ref_name }}
      
      - name: Build docker compose
        run: docker-compose build --build-arg RELEASE_TAG
      
      - name: Publish docker compose
        run: docker-compose push